### ISSUE TITLE
30kwh battery degredation

### ISSUE THREAD

**Issue by raffertyparker** [samholford/leafguide#1]
Hi Sam,
Flip the Fleet have updated their position on 30kWh batteries, with new information that shows that the early degradation is actually a firmware issue rather than an issue with the batteries.

"We therefore conclude that much of our earlier concern about rapidly declining reported SoH stemmed from an instrumentation error rather than degradation of the battery itself."
https://flipthefleet.org/2018/30-kwh-nissan-leaf-firmware-update-to-correct-capacity-reporting/

**Comment by samholford** [comment]
Thanks. I've made a small update and removed this concern.
